augs:
  LR: 0.5
  UD: 0.0
  brightness: 0.25
  color_p: 0.5
  contrast: 0.1
  crop_size: null
  dali: false
  degrees: 10
  grayscale: 0.5
  hue: 0.1
  normalization:
    N: 134573787500
    mean:
    - 0.4188662543741402
    - 0.384645660879449
    - 0.3572427996897448
    std:
    - 0.18899837086842783
    - 0.1915122234643136
    - 0.19592325647909137
  pad: null
  random_resize: false
  resize:
  - 224
  - 224
  saturation: 0.1
compute:
  batch_size: 8
  dali: false
  distributed: false
  fp16: false
  gpu_id: 0
  max_batch_size: 512
  metrics_workers: 0
  min_batch_size: 8
  num_workers: 3
feature_extractor:
  arch: resnet18
  curriculum: false
  dropout_p: 0.25
  final_activation: sigmoid
  final_bn: false
  fusion: average
  inputs: both
  n_flows: 10
  n_rgb: 1
  sampler: null
  sampling_ratio: null
  weights: D:\SIT_auto\SIT_deepethogram\models\250715_141521_feature_extractor_train\lightning_checkpoints\epoch=0-step=999.ckpt
flow_generator:
  arch: TinyMotionNet
  flow_loss: MotionNet
  flow_max: 10
  flow_sparsity: false
  input_images: 11
  loss: MotionNet
  max: 5
  n_rgb: 11
  smooth_weight_multiplier: 1.0
  sparsity_weight: 0.0
  type: flow_generator
  weights: D:\SIT_auto\SIT_deepethogram\models\250715_120117_flow_generator_train\lightning_checkpoints\epoch=1-step=1999.ckpt
inference:
  directory_list:
  - D:\SIT_auto\SIT_deepethogram\DATA\SIT1-JNG-77-4-2025-04-1509-04-17
  - D:\SIT_auto\SIT_deepethogram\DATA\SIT13-KU2-78-3-2025-04-1609-26-39
  - D:\SIT_auto\SIT_deepethogram\DATA\SIT15-DOA-77-3-2025-04-1610-03-51
  - D:\SIT_auto\SIT_deepethogram\DATA\SIT17-BQ9-78-2-2025-04-1610-40-34
  - D:\SIT_auto\SIT_deepethogram\DATA\SIT19-6VT-77-1-2025-04-1611-17-34
  - D:\SIT_auto\SIT_deepethogram\DATA\SIT20-KUS-80-3-2025-04-1708-49-12
  - D:\SIT_auto\SIT_deepethogram\DATA\SIT22-TKX-80-5-2025-04-1709-27-09
  - D:\SIT_auto\SIT_deepethogram\DATA\SIT24-XBE-79-2-2025-04-1710-03-11
  - D:\SIT_auto\SIT_deepethogram\DATA\SIT26-69B-80-1-2025-04-1710-41-04
  - D:\SIT_auto\SIT_deepethogram\DATA\SIT3-CV4-78-3-2025-04-1509-42-29
  - D:\SIT_auto\SIT_deepethogram\DATA\SIT7-H38-78-2-2025-04-1511-01-21
  - D:\SIT_auto\SIT_deepethogram\DATA\SIT9-J1S-77-1-2025-04-1511-40-13
  - D:\SIT_auto\SIT_deepethogram\DATA\Sit11-CJ6-78-1-2025-04-1608-48-16
  - D:\SIT_auto\SIT_deepethogram\DATA\Sit5-E4I-77-2-2025-04-1510-20-38
  ignore_error: true
  overwrite: true
  use_loaded_model_cfg: true
log:
  level: info
notes: null
postprocessor:
  min_bout_length: 1
  type: min_bout_per_behavior
project:
  class_names:
  - background
  - Contactbyhost
  - Contactbyvisitor
  - Followbyhost
  - Followbyvisitor
  - Pawcontrol(host)
  - Rearing
  - Tailrattling
  - Grooming
  config_file: D:\SIT_auto\SIT_deepethogram\project_config.yaml
  data_path: D:\SIT_auto\SIT_deepethogram\DATA
  labeler: null
  model_path: D:\SIT_auto\SIT_deepethogram\models
  name: SIT
  path: D:\SIT_auto\SIT_deepethogram
  pretrained_path: D:\SIT_auto\SIT_deepethogram\models\pretrained_models
reload:
  latest: false
  overwrite_cfg: false
run:
  dir: D:\SIT_auto\SIT_deepethogram\models\250715_145220_feature_extractor_inference
  model: feature_extractor
  type: inference
sequence:
  filter_length: 15
split:
  file: null
  reload: true
  train_val_test:
  - 0.8
  - 0.2
  - 0.0
train:
  loss_weight_exp: 1.0
  num_epochs: 10
  steps_per_epoch:
    test: 20
    train: 1000
    val: 200
