augs:
  LR: 0.5
  UD: 0.0
  brightness: 0.25
  contrast: 0.1
  crop_size: null
  degrees: 10
  grayscale: 0.5
  hue: 0.1
  normalization:
    N: 134573787500
    mean:
    - 0.4188662543741402
    - 0.384645660879449
    - 0.3572427996897448
    std:
    - 0.18899837086842783
    - 0.1915122234643136
    - 0.19592325647909137
  pad: null
  random_resize: false
  resize:
  - 224
  - 224
  saturation: 0.1
compute:
  batch_size: 8
  distributed: false
  gpu_id: 0
  num_workers: 3
project:
  class_names:
  - background
  - Contactbyhost
  - Contactbyvisitor
  - Followbyhost
  - Followbyvisitor
  - Pawcontrol(host)
  - Rearing
  - Tailrattling
  - Grooming
  config_file: project_config.yaml
  data_path: DATA
  labeler: null
  model_path: models
  name: SIT
  path: D:\SIT_auto\SIT_deepethogram
  pretrained_path: pretrained_models
sequence:
  filter_length: 15
split:
  file: null
  reload: true
train:
  loss_weight_exp: 1.0
